### PR TITLE
Update README with new syntax

### PR DESCRIPTION
**Pull request by MarceloAlves**
HCL syntax is out. Long live YAML!

### CODE REVIEW

**Review by JasonSoares — APPROVED** [review]
💯

**Comment by gitblit** [comment]
I really want to try this capability for PR tests and maybe Nuget publishing to GH.

**Comment by gitblit** [comment]
This is my blueprint - stolen from some other repo.

```
name: dotnet core - build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      run: dotnet build --configuration Release
    - name: Unit Tests
      run: dotnet test
    - name: Build NuGet Package
      run: dotnet pack ./src/HtmlMinificationMiddleware/HtmlMinificationMiddleware.csproj --configuration Release -o NuGetPackages
    - name: Deploy NuGet Package
      run: dotnet nuget push ./src/HtmlMinificationMiddleware/NuGetPackages/HtmlMinificationMiddleware.2.2.1.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
```

**Comment by MarceloAlves** [comment]
:shipit:

For `on` you can limit it to branches and all that

```yaml
on:
  push:
    branches: [master, develop]
  pull_request:
    types: [opened]
```

also if you don't want to push to nuget on PR you can add `if`

```yaml
- name: Deploy NuGet Package
  if: github.event_name != 'pull_request'
  run: ....
```

**Pull request merged**
